version: '3.8'
services:
  db:
    image: postgres:16
    container_name: haustiere-db
    restart: always
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: haustiere-postgres
